// app/tag/page.tsx
import Link from "next/link"
import { getAllTags } from "@/lib/posts"

export default function TagIndexPage() {
  const tags = getAllTags()

  if (Object.keys(tags).length === 0) {
    return (
      <div className="page-container">
        <h1 className="page-title">Tags</h1>
        <p className="empty-message">No tags yet.</p>
      </div>
    )
  }

  return (
    <div className="page-container">
      <h1 className="page-title">Tags</h1>
      <div className="tag-cloud">
        {Object.entries(tags).map(([tag, count]) => (
          <Link
            key={tag}
            href={`/tag/${encodeURIComponent(tag)}`}
            className="tag-item"
          >
            {tag}
            <sup className="tag-count">{count}</sup>
          </Link>
        ))}
      </div>
    </div>
  )
}

// src/routes/tag/+page.svelte
<script lang="ts">
  let { data }: { data: { tags: Record<string, number> } } = $props()
</script>

<div class="page-container">
  <h1 class="page-title">Tags</h1>
  {#if Object.keys(data.tags).length === 0}
    <p class="empty-message">No tags yet.</p>
  {:else}
    <div class="tag-cloud">
      {#each Object.entries(data.tags) as [tag, count]}
        <a href={`/tag/${encodeURIComponent(tag)}`} class="tag-item">
          {tag}<sup class="tag-count">{count}</sup>
        </a>
      {/each}
    </div>
  {/if}
</div>
