// src/routes/posts/[slug]/+page.svelte
<script lang="ts">
  import type { PostMeta } from "$lib/constants"
  import { siteConfig } from "$lib/constants"
  import MarkdownRenderer from "$lib/components/MarkdownRenderer.svelte"
  import PostNav from "$lib/components/PostNav.svelte"
  import TOC from "$lib/components/TOC.svelte"

  let { data }: { data: { post: PostMeta; prev: PostMeta | null; next: PostMeta | null; permalink: string } } = $props()
</script>

<div class="post-layout">
  <article class="post-article">
    <header class="post-header">
      <h1 class="post-title">{data.post.title}</h1>
      <div class="post-meta">
        {#if siteConfig.author}
          <span class="post-author">{siteConfig.author}</span>
        {/if}
        {#if data.post.date}
          <span class="post-date">{data.post.date}</span>
        {/if}
        {#if data.post.categories.length > 0}
          <span class="post-categories">{data.post.categories.join(", ")}</span>
        {/if}
      </div>
    </header>

    <MarkdownRenderer content={data.post.content} />

    <PostNav prev={data.prev} next={data.next} />
  </article>

  <TOC />
</div>

// app/posts/[slug]/page.tsx
import { notFound } from "next/navigation"
import { getAllPosts, getPostBySlug, getAdjacentPosts } from "@/lib/posts"
import { siteConfig } from "@/lib/constants"
import MarkdownRenderer from "./MarkdownRenderer"
import Copyright from "@/components/Copyright"
import PostNav from "@/components/PostNav"
import TOC from "@/components/TOC"

export async function generateStaticParams() {
  return getAllPosts().map((p) => ({ slug: p.slug }))
}

export default async function PostPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const post = getPostBySlug(slug)
  if (!post) notFound()

  const { prev, next } = getAdjacentPosts(slug)
  const permalink = `${siteConfig.url}/posts/${slug}`

  return (
    <div className="post-layout">
      <article className="post-article">
        <header className="post-header">
          <h1 className="post-title">{post.title}</h1>
          <div className="post-meta">
            {siteConfig.author && <span className="post-author">{siteConfig.author}</span>}
            {post.date && <span className="post-date">{post.date}</span>}
            {post.categories.length > 0 && (
              <span className="post-categories">
                {post.categories.join(", ")}
              </span>
            )}
          </div>
        </header>

        <div className="post-content">
          <MarkdownRenderer content={post.content} />
        </div>

        <Copyright permalink={permalink} />
        <PostNav prev={prev} next={next} />
      </article>

      <TOC />
    </div>
  )
}
