// src/routes/tag/[name]/+page.svelte
<script lang="ts">
  import type { PostMeta } from "$lib/constants"

  let { data }: { data: { name: string; posts: PostMeta[] } } = $props()
</script>

<div class="page-container">
  <h1 class="page-title">
    Tag: <span class="page-subtitle">{data.name}</span>
  </h1>
  {#each data.posts as post}
    <div class="archive-item">
      <span class="archive-date">{post.date?.replace(/-/g, "/")}</span>
      <a href={`/posts/${post.slug}`} class="archive-link">{post.title}</a>
    </div>
  {/each}
</div>

// app/tag/[name]/page.tsx
import Link from "next/link"
import { notFound } from "next/navigation"
import { getPostsByTag, getAllTags } from "@/lib/posts"

export async function generateStaticParams() {
  return Object.keys(getAllTags()).map((name) => ({ name }))
}

export default async function TagPage({ params }: { params: Promise<{ name: string }> }) {
  const { name } = await params
  const posts = getPostsByTag(decodeURIComponent(name))
  if (posts.length === 0) notFound()

  return (
    <div className="page-container">
      <h1 className="page-title">
        Tag: <span className="page-subtitle">{decodeURIComponent(name)}</span>
      </h1>
      {posts.map((post) => (
        <div key={post.slug} className="archive-item">
          <span className="archive-date">{post.date?.replace(/-/g, "/")}</span>
          <Link href={`/posts/${post.slug}`} className="archive-link">
            {post.title}
          </Link>
        </div>
      ))}
    </div>
  )
}
