// src/lib/components/Paginator.svelte
<script lang="ts">
  let { current, total, basePath }: { current: number; total: number; basePath: string } = $props()

  let pages = $derived.by(() => {
    if (total <= 1) return null
    const p: (number | "...")[] = []
    for (let i = 1; i <= total; i++) {
      if (i === 1 || i === total || (i >= current - 1 && i <= current + 1)) {
        p.push(i)
      } else if (p[p.length - 1] !== "...") {
        p.push("...")
      }
    }
    return p
  })
</script>

{#if pages}
  <nav class="paginator">
    {#each pages as p, i}
      {#if p === "..."}
        <span class="paginator-dots">...</span>
      {:else}
        <a
          href={p === 1 ? basePath : `${basePath}/page/${p}`}
          class="paginator-page"
          class:active={p === current}
        >
          {p}
        </a>
      {/if}
    {/each}
  </nav>
{/if}

// components/Paginator.tsx
import Link from "next/link"

export default function Paginator({
  current,
  total,
  basePath,
}: {
  current: number
  total: number
  basePath: string
}) {
  if (total <= 1) return null
  const pages: (number | "...")[] = []
  for (let i = 1; i <= total; i++) {
    if (i === 1 || i === total || (i >= current - 1 && i <= current + 1)) {
      pages.push(i)
    } else if (pages[pages.length - 1] !== "...") {
      pages.push("...")
    }
  }

  return (
    <nav className="paginator">
      {pages.map((p, i) =>
        p === "..." ? (
          <span key={`dots-${i}`} className="paginator-dots">
            ...
          </span>
        ) : (
          <Link
            key={p}
            href={p === 1 ? basePath : `${basePath}/page/${p}`}
            className={`paginator-page${p === current ? " active" : ""}`}
          >
            {p}
          </Link>
        ),
      )}
    </nav>
  )
}
