// src/routes/archives/+page.svelte
<script lang="ts">
  let { data }: { data: { grouped: Record<string, Array<{ slug: string; title: string; date: string }>>; total: number } } = $props()
</script>

<div class="page-container">
  <h1 class="page-title">Archives</h1>
  {#each Object.entries(data.grouped) as [year, yearPosts]}
    <div class="archive-year">
      <h2 class="archive-year-title">{year}</h2>
      {#each yearPosts as post}
        <div class="archive-item">
          <span class="archive-date">{post.date?.replace(/-/g, "/")}</span>
          <a href={`/posts/${post.slug}`} class="archive-link">{post.title}</a>
        </div>
      {/each}
    </div>
  {/each}
  {#if data.total === 0}
    <p class="empty-message">No posts yet.</p>
  {/if}
</div>

// app/archives/page.tsx
import Link from "next/link"
import { getAllPosts } from "@/lib/posts"

export default function ArchivesPage() {
  const posts = getAllPosts()

  const grouped: Record<string, typeof posts> = {}
  for (const post of posts) {
    const year = post.date?.slice(0, 4) || "Unknown"
    if (!grouped[year]) grouped[year] = []
    grouped[year].push(post)
  }

  return (
    <div className="page-container">
      <h1 className="page-title">Archives</h1>
      {Object.entries(grouped).map(([year, yearPosts]) => (
        <div key={year} className="archive-year">
          <h2 className="archive-year-title">{year}</h2>
          {yearPosts.map((post) => (
            <div key={post.slug} className="archive-item">
              <span className="archive-date">{post.date?.replace(/-/g, "/")}</span>
              <Link href={`/posts/${post.slug}`} className="archive-link">
                {post.title}
              </Link>
            </div>
          ))}
        </div>
      ))}
      {posts.length === 0 && <p className="empty-message">No posts yet.</p>}
    </div>
  )
}
