// components/PostNav.tsx
import Link from "next/link"
import type { PostMeta } from "@/lib/constants"

export default function PostNav({
  prev,
  next,
}: {
  prev: PostMeta | null
  next: PostMeta | null
}) {
  return (
    <div className="post-nav">
      {prev ? (
        <Link href={`/posts/${prev.slug}`} className="post-nav-prev">
          <span className="post-nav-arrow">‹</span>
          <span>{prev.title}</span>
        </Link>
      ) : (
        <span />
      )}
      {next ? (
        <Link href={`/posts/${next.slug}`} className="post-nav-next">
          <span>{next.title}</span>
          <span className="post-nav-arrow">›</span>
        </Link>
      ) : (
        <span />
      )}
    </div>
  )
}

// src/lib/components/PostNav.svelte
<script lang="ts">
  import type { PostMeta } from "$lib/constants"

  let { prev, next }: { prev: PostMeta | null; next: PostMeta | null } = $props()
</script>

<div class="post-nav">
  {#if prev}
    <a href={`/posts/${prev.slug}`} class="post-nav-prev">
      <span class="post-nav-arrow">‹</span>
      <span>{prev.title}</span>
    </a>
  {:else}
    <span></span>
  {/if}
  {#if next}
    <a href={`/posts/${next.slug}`} class="post-nav-next">
      <span>{next.title}</span>
      <span class="post-nav-arrow">›</span>
    </a>
  {:else}
    <span></span>
  {/if}
</div>
